import SwiftUI

struct AllRecipesModel {
    let australiaImage = [ImageName.aussieDelight.rawValue]
    let australiaName = ["Aussie Delight"]
    
    var austria = DishAndQiuzz(imageNameContry: ImageName.australiaLabel.rawValue,
                               imageForFav: ImageName.aussieDelight.rawValue,
                               imageCandy: ImageName.candy.rawValue,
                               imageDish: ImageName.quizAustria.rawValue,
                               nameOfDish: "AUSSIE DELIGHT",
                               historyOfDish: "In the heart of Australia, nestled between the vibrant cities and the vast outback, lies a small town named Sweet Haven. This town is renowned for its unique and delicious desserts, which have become a symbol of Australian hospitality and creativity. The story of the Aussie Delight begins with a young pastry chef named Emily, who had a dream to create a dessert that would capture the essence of Australia's diverse flavors and vibrant spirit.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.\n\u{2022} In a large bowl, combine the flour, sugar, cocoa powder, baking powder, baking soda, salt, and espresso powder.\n\u{2022} Add the milk, vegetable oil, eggs, and vanilla extract. Mix until well combined.\n\u{2022} Stir in the boiling water (the batter will be thin).\n\u{2022} Pour the batter into the prepared pans and bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean",
                                      ingredients: "\u{2022} 2 cups all-purpose flour\n\u{2022} 2 cups granulated sugar\n\u{2022} 3/4 cup unsweetened cocoa powder\n\u{2022} 2 teaspoons baking powder\n\u{2022} 1 1/2 teaspoons baking soda\n\u{2022} 1 teaspoon salt\n\u{2022} 1 teaspoon espresso powder\n\u{2022} 1 cup milk\n\u{2022} 1/2 cup vegetable oil\n\u{2022} 2 eggs\n\u{2022} 2 teaspoons vanilla extract\n\u{2022} 1 cup boiling water",
                                      height: 0.475,
                               quizz: Quizzes(questions: ["WHO CREATED THE AUSSIE DELIGHT?",
                                                          "What inspired the creation of the Aussie Delight?"],
                                              answers: [["A. a famous tv chef",
                                                         "B. A young pastry chef named Emily",
                                                         "C. A renowned bakery chain",
                                                         "D. An Australian celebrity"],
                                                        
                                                        ["A. Traditional Australian recipes",
                                                         "B. Emily's travels across Australia",
                                                         "C. International dessert trends",
                                                         "D. A cooking competition"]],
                                              rightAnswers: ["B. A young pastry chef named Emily",
                                                             "B. Emily's travels across Australia"]))
    
    var europe1 = DishAndQiuzz(imageNameContry: ImageName.europeLabel.rawValue,
                               imageForFav: ImageName.tropicalCake.rawValue,
                               imageCandy: ImageName.europeCandy.rawValue,
                               imageDish: ImageName.europe1.rawValue,
                               nameOfDish: "Tropical Sunrise Cake",
                               historyOfDish: "The Tropical Sunrise Cake was inspired by the vibrant sunrises of Queensland, Australia. A local baker, named Lily, wanted to capture the essence of the tropical paradise in a dessert. She combined fresh pineapples, mangoes, and kiwis with a light, fluffy sponge cake and topped it with a creamy frosting. The cake quickly became a favorite at local markets and is now a staple at Australian summer celebrations.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.\n\u{2022} In a large bowl, combine the flour, sugar, cocoa powder, baking powder, baking soda, salt, and espresso powder.\n\u{2022} Add the milk, vegetable oil, eggs, and vanilla extract. Mix until well combined.\n\u{2022} Stir in the boiling water (the batter will be thin).\n\u{2022} Pour the batter into the prepared pans and bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean",
                               ingredients: "\u{2022} 2 cups all-purpose flour\n\u{2022} 2 cups granulated sugar\n\u{2022} 3/4 cup unsweetened cocoa powder\n\u{2022} 2 teaspoons baking powder\n\u{2022} 1 1/2 teaspoons baking soda\n\u{2022} 1 teaspoon salt\n\u{2022} 1 teaspoon espresso powder\n\u{2022} 1 cup milk\n\u{2022} 1/2 cup vegetable oil\n\u{2022} 2 eggs\n\u{2022} 2 teaspoons vanilla extract\n\u{2022} 1 cup boiling water",
                                      height: 0.375,
                               quizz: Quizzes(questions: ["What inspired the creation of the Tropical Sunrise Cake?",
                                                          "Which fruits are typically used in the Tropical Sunrise Cake?"],
                                              answers: [["A. The vibrant sunrises of Queensland",
                                                         "B. The bustling markets of Sydney",
                                                         "C. The cool climate of Tasmania",
                                                         "D. The desert landscapes of the Outback"],
                                                        
                                                        ["A. Apples and pears",
                                                         "B. Pineapple, mango, and kiwi",
                                                         "C. Bananas and oranges",
                                                         "D. Grapes and melons"]],
                                              rightAnswers: ["A. The vibrant sunrises of Queensland",
                                                             "B. Pineapple, mango, and kiwi"]))
    
    var europe2 = DishAndQiuzz(imageNameContry: ImageName.europeLabel.rawValue,
                               imageForFav: ImageName.unionJake.rawValue,
                               imageCandy: ImageName.europeCandy.rawValue,
                               imageDish: ImageName.europe2.rawValue,
                               nameOfDish: "Union Jack Cupcake",
                               historyOfDish: "The Union Jack Cupcake was created by a British expat living in Sydney. Missing the flavors of home, she decided to blend traditional British baking with Australian ingredients. The cupcake features a moist vanilla base, topped with a swirl of rich cream cheese frosting. The Union Jack design on the wrapper is a nod to her British heritage, making it a hit among both locals and expats.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Line a muffin tin with cupcake liners.\n\u{2022} In a large bowl, cream the butter and sugar until light and fluffy.\n\u{2022} Add the eggs, one at a time, mixing well after each addition.\n\u{2022} In another bowl, combine the flour, baking powder, and salt.\n\u{2022} Gradually add the dry ingredients to the wet ingredients, alternating with the milk.\n\u{2022} Stir in the vanilla extract.",
                               ingredients: "\u{2022} 1 1/2 cups all-purpose flour\n\u{2022} 1 cup granulated sugar\n\u{2022} 1/2 cup unsalted butter, softened\n\u{2022} 2 large eggs\n\u{2022} 1/2 cup milk\n\u{2022} 1 1/2 teaspoons baking powder\n\u{2022} 1 teaspoon vanilla extract\n\u{2022} 1/4 teaspoon salt",
                                      height: 0.375,
                               quizz: Quizzes(questions: ["Who created the Union Jack Cupcake?",
                                                          "What inspired the creation of the Union Jack Cupcake?"],
                                              answers: [["A. A British expat living in Sydney",
                                                         "B. A local Australian baker",
                                                         "C. A famous pastry chef from London",
                                                         "D. An Australian celebrity chef"],
                                                        
                                                        ["A. The flavors of traditional British baking",
                                                         "B. The desire to blend Australian and British ingredients",
                                                         "C. The need for a simple and classic dessert",
                                                         "D. The popularity of international dessert trends"]],
                                              rightAnswers: ["A. A British expat living in Sydney",
                                                             "A. The flavors of traditional British baking"]))
    
    var europe3 = DishAndQiuzz(imageNameContry: ImageName.europeLabel.rawValue,
                               imageForFav: ImageName.asia1.rawValue,
                               imageCandy: ImageName.europeCandy.rawValue,
                               imageDish: ImageName.europe3.rawValue,
                               nameOfDish: "Golden Wattle Delight",
                               historyOfDish: "The Golden Wattle Delight was inspired by Australia's national floral emblem, the golden wattle. A pastry chef in Adelaide, named Sarah, wanted to create a dessert that embodied the beauty and elegance of the wattle. She crafted a chocolate cake with layers of cream and topped it with a golden leaf, resembling the wattle's bloom. The cake is now a popular choice for special occasions and celebrations.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.\n\u{2022} In a large bowl, combine the flour, sugar, cocoa powder, baking powder, baking soda, salt, and espresso powder.\n\u{2022} Add the milk, vegetable oil, eggs, and vanilla extract. Mix until well combined.\n\u{2022} Stir in the boiling water (the batter will be thin).\n\u{2022} Pour the batter into the prepared pans and bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean.",
                               ingredients: "\u{2022} 2 cups all-purpose flour\n\u{2022} 2 cups granulated sugar\n\u{2022} 3/4 cup unsweetened cocoa powder\n\u{2022} 2 teaspoons baking powder\n\u{2022} 1 1/2 teaspoons baking soda\n\u{2022} 1 teaspoon salt\n\u{2022} 1 teaspoon espresso powder\n\u{2022} 1 cup milk\n\u{2022} 1/2 cup vegetable oil \n\u{2022} 2 eggs\n\u{2022} 2 teaspoons vanilla extract\n\u{2022} 1 cup boiling water",
                                      height: 0.375,
                               quizz: Quizzes(questions: ["What inspired the creation of the Golden Wattle Delight?",
                                                          "Who created the Golden Wattle Delight?"],
                                              answers: [["A. Australia's national floral emblem, the golden wattle",
                                                         "B. The vibrant sunrises of Queensland",
                                                         "C. The cool climate of Tasmania",
                                                         "D. The desert landscapes of the Outback"],
                                                        
                                                        ["A. A pastry chef in Adelaide named Sarah",
                                                         "B. A local baker named Lily",
                                                         "C. A renowned pastry chef from Melbourne",
                                                         "D. An Australian celebrity"]],
                                              rightAnswers: ["A. Australia's national floral emblem, the golden wattle",
                                                             "A. A pastry chef in Adelaide named Sarah"]))
    
    var africa1 = DishAndQiuzz(imageNameContry: ImageName.africaLabel.rawValue,
                               imageForFav: ImageName.africa1.rawValue,
                               imageCandy: ImageName.africaCandy.rawValue,
                               imageDish: ImageName.afric1.rawValue,
                               nameOfDish: "African Sunset Fruit Tart",
                               historyOfDish: "The African Sunset Fruit Tart was inspired by the breathtaking sunsets of the African savannah. A talented pastry chef named Amina, who grew up in a small village in Kenya, wanted to bring the vibrant colors and flavors of Africa to the world through her desserts. She created a tart filled with a creamy custard and topped with an array of fresh, tropical fruits that mimic the hues of an African sunset. The tart became an instant hit at local markets and is now a favorite at celebrations across Africa and beyond.",
                               receptOfDish: "\u{2022} In a food processor, combine the flour and powdered sugar.\n\u{2022} Add the cubed butter and pulse until the mixture resembles coarse crumbs. Add the egg yolk and pulse until combined.\n\u{2022} Add the milk, vegetable oil, eggs, and vanilla extract. Mix until well combined.\n\u{2022} Gradually add the cold water, one tablespoon at a time, until the dough comes together.\n\u{2022} Press the dough into a 9-inch tart pan with a removable bottom, covering the bottom and sides evenly.\n\u{2022} Chill the crust in the refrigerator for 30 minutes.",
                               ingredients: "\u{2022} 1 1/2 cups all-purpose flour\n\u{2022} 1/2 cup powdered sugar\n\u{2022} 1/2 cup cold unsalted butter, cubed\n\u{2022} 1 large egg yolk\n\u{2022} 1-2 tablespoons cold water",
                                      height: 0.32,
                               quizz: Quizzes(questions: ["Who created the African Sunset Fruit Tart?",
                                                          "What inspired the creation of the African Sunset Fruit Tart?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A talented pastry chef named Amina",
                                                         "C. A renowned baker from South Africa",
                                                         "D. An African celebrity"],
                                                        
                                                        ["A. The vibrant sunsets of the African savannah",
                                                         "B. The bustling markets of Nairobi",
                                                         "C. The cool climate of the highlands",
                                                         "D. The desert landscapes of the Sahara"]],
                                              rightAnswers: ["A. A famous TV chef",
                                                             "A. The vibrant sunsets of the African savannah"]))
    
    var africa2 = DishAndQiuzz(imageNameContry: ImageName.africaLabel.rawValue,
                               imageForFav: ImageName.africa2.rawValue,
                               imageCandy: ImageName.africaCandy.rawValue,
                               imageDish: ImageName.afric2.rawValue,
                               nameOfDish: "Safari Delight Mango Pudding",
                               historyOfDish: "The Safari Delight Mango Pudding was created by a young chef named Kofi, who was born and raised in the lush landscapes of Ghana. Inspired by the vibrant colors and flavors of the African savannah, Kofi wanted to capture the essence of a safari adventure in a dessert. He blended the sweetness of ripe mangoes with the creaminess of coconut milk to create a refreshing and tropical pudding. The dessert quickly became a favorite at local festivals and is now enjoyed across Africa and beyond.",
                               receptOfDish: "\u{2022} Add the coconut milk to the mango puree in the saucepan and stir well.\n\u{2022} In a small bowl, mix the cornstarch with 1/4 cup cold water until smooth.\n\u{2022} Pour the cornstarch mixture into the saucepan and stir continuously over medium heat until the mixture thickens.\n\u{2022} Remove from heat and stir in the vanilla extract.\n\u{2022} Pour the pudding into individual serving dishes and chill in the refrigerator for at least 2 hours.",
                               ingredients: "\u{2022} 2 ripe mangoes, peeled and diced\n\u{2022} 1/2 cup granulated sugar\n\u{2022} 1/2 cup water\n\u{2022} 1 can (14 oz) coconut milk\n\u{2022} 1/4 cup cornstarch\n\u{2022} 1/4 cup cold water\n\u{2022} 1 teaspoon vanilla extract",
                                      height: 0.32,
                               quizz: Quizzes(questions: ["Who created the Safari Delight Mango Pudding?",
                                                          "What inspired the creation of the Safari Delight Mango Pudding?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A young chef named Kofi",
                                                         "C. A renowned baker from Nigeria",
                                                         "D. An African celebrity"],
                                                        
                                                        ["A. The vibrant colors and flavors of the African savannah",
                                                         "B. The bustling markets of Accra",
                                                         "C. The cool climate of the highlands",
                                                         "D. The coastal landscapes of Cape Town"]],
                                              rightAnswers: ["A. A famous TV chef",
                                                             "A. The vibrant colors and flavors of the African savannah"]))
    
    var africa3 = DishAndQiuzz(imageNameContry: ImageName.africaLabel.rawValue,
                               imageForFav: ImageName.africa3.rawValue,
                               imageCandy: ImageName.africaCandy.rawValue,
                               imageDish: ImageName.afric3.rawValue,
                               nameOfDish: "Savannah Sunrise Fruit Salad",
                               historyOfDish: "The Savannah Sunrise Fruit Salad was created by a passionate chef named Nala, who grew up in the heart of the African savannah in Tanzania. Inspired by the stunning sunrises and the abundance of fresh fruits in her homeland, Nala wanted to create a dessert that celebrated the natural beauty of Africa. She combined a variety of tropical fruits with a tangy dressing to create a refreshing and vibrant fruit salad. The dessert quickly became a staple at family gatherings and is now enjoyed across Africa.",
                               receptOfDish: "\u{2022} In a large bowl, combine the diced pineapple, mango, sliced kiwi, strawberries, blueberries, raspberries, and pomegranate seeds.\n\u{2022} In a small bowl, whisk together the orange juice, honey, lime juice, and grated ginger until well combined.\n\u{2022} Pour the dressing over the fruit mixture and gently toss to coat evenly.\n\u{2022} Garnish with fresh mint leaves before serving.",
                               ingredients: "\u{2022} 1 cup diced pineapple\n\u{2022} 1 cup diced mango\n\u{2022} 1 cup sliced kiwi\n\u{2022} 1 cup sliced strawberries\n\u{2022} 1/2 cup blueberries\n\u{2022} 1/2 cup raspberries\n\u{2022} 1/4 cup pomegranate seeds",
                                      height: 0.32,
                               quizz: Quizzes(questions: ["Who created the Savannah Sunrise Fruit Salad?",
                                                          "What inspired the creation of the Savannah Sunrise Fruit Salad?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A passionate chef named Nala",
                                                         "C. A renowned baker from Kenya",
                                                         "D. An African celebrity"],
                                                        
                                                        ["A. The stunning sunrises of the African savannah",
                                                         "B. The bustling markets of Dar es Salaam",
                                                         "C. The cool climate of the highlands",
                                                         "D. The desert landscapes of the Sahara"]],
                                              rightAnswers: ["B. A passionate chef named Nala",
                                                             "A. The stunning sunrises of the African savannah"]))
    
    var asia1 = DishAndQiuzz(imageNameContry: ImageName.asiaLabel.rawValue,
                             imageForFav: ImageName.asia1.rawValue,
                               imageCandy: ImageName.asianCandy.rawValue,
                               imageDish: ImageName.asian1.rawValue,
                               nameOfDish: "Jade Dragon Fruit Cake",
                               historyOfDish: "The Jade Dragon Fruit Cake was created by a talented pastry chef named Mei Li, who grew up in the bustling city of Shanghai. Inspired by the rich cultural heritage and vibrant colors of China, Mei Li wanted to create a dessert that embodied the elegance and beauty of her homeland. She combined the exotic flavors of dragon fruit with the delicate sweetness of lychee and the creaminess of coconut to create a stunning and delicious cake. The Jade Dragon Fruit Cake quickly became a sensation at local tea houses and is now a beloved dessert across China.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.\n\u{2022} In a large bowl, combine the flour, sugar, baking powder, and salt.\n\u{2022} In another bowl, mix the eggs, vegetable oil, coconut milk, vanilla extract, and a few drops of pink food coloring (if using).\n\u{2022} Combine the wet and dry ingredients and mix until smooth.\n\u{2022} Pour the batter into the prepared pans and bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.\n\u{2022} Allow the cakes to cool completely.",
                               ingredients: "\u{2022} 2 cups all-purpose flour\n\u{2022} 2 cups granulated sugar\n\u{2022} 4 large eggs\n\u{2022} 1 cup vegetable oil\n\u{2022} 1 cup coconut milk\n\u{2022} 2 teaspoons baking powder\n\u{2022} 1 teaspoon vanilla extract\n\u{2022} 1/2 teaspoon salt\n\u{2022} Pink food coloring (optional)",
                                      height: 0.27,
                               quizz: Quizzes(questions: ["Who created the Jade Dragon Fruit Cake?",
                                                          "What inspired the creation of the Jade Dragon Fruit Cake?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A talented pastry chef named Mei Li",
                                                         "C. A renowned baker from Beijing",
                                                         "D. A Chinese celebrity"],
                                                        
                                                        ["A. The rich cultural heritage of China",
                                                         "B. The bustling markets of Guangzhou",
                                                         "C. The cool climate of the mountains",
                                                         "D. The desert landscapes of the Gobi"]],
                                              rightAnswers: ["B. A talented pastry chef named Mei Li",
                                                             "A. The rich cultural heritage of China"]))
    
    var asia2 = DishAndQiuzz(imageNameContry: ImageName.asiaLabel.rawValue,
                             imageForFav: ImageName.asia2.rawValue,
                               imageCandy: ImageName.asianCandy.rawValue,
                               imageDish: ImageName.asian2.rawValue,
                               nameOfDish: "Lucky Red Bean Mooncake",
                               historyOfDish: "The Lucky Red Bean Mooncake was created by a skilled baker named Li Wei, who hails from the historic city of Xi'an. Inspired by the traditional Mid-Autumn Festival and the significance of the moon in Chinese culture, Li Wei wanted to create a dessert that celebrated the joy and unity of the festival. He combined the sweetness of red bean paste with the delicate flavors of lotus seed paste and the richness of salted egg yolks to create a traditional yet innovative mooncake. The Lucky Red Bean Mooncake quickly became a favorite during the festival and is now enjoyed year-round.",
                               receptOfDish: "\u{2022} In a large bowl, combine the flour, golden syrup, vegetable oil, and lye water. Mix until a smooth dough forms.\n\u{2022} Cover the dough with plastic wrap and let it rest for 30 minutes.\n\u{2022} In a saucepan, combine the red bean paste, sugar, and vegetable oil. Cook over medium heat until the mixture thickens.\n\u{2022} Let it cool.",
                               ingredients: "\u{2022} For the Mooncake Dough:\n\u{2022} 2 cups all-purpose flour\n\u{2022} 1 cup golden syrup\n\u{2022} 1/2 cup vegetable oil\n\u{2022} 1/2 teaspoon lye water (kansui)\n\u{2022} For the Red Bean Filling:\n\u{2022} 1 cup red bean paste\n\u{2022} 1/4 cup granulated sugar\n\u{2022} 1 tablespoon vegetable oil",
                                      height: 0.27,
                               quizz: Quizzes(questions: ["Who created the Lucky Red Bean Mooncake?",
                                                          "What inspired the creation of the Lucky Red Bean Mooncake?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A skilled baker named Li Wei",
                                                         "C. A renowned pastry chef from Shanghai",
                                                         "D. A Chinese celebrity"],
                                                        
                                                        ["A. The traditional Mid-Autumn Festival",
                                                         "B. The bustling markets of Beijing",
                                                         "C. The cool climate of the mountains",
                                                         "D. The significance of the dragon in Chinese culture"]],
                                              rightAnswers: ["B. A skilled baker named Li Wei",
                                                             "A. The traditional Mid-Autumn Festival"]))
    
    var asia3 = DishAndQiuzz(imageNameContry: ImageName.asiaLabel.rawValue,
                             imageForFav: ImageName.asia3.rawValue,
                               imageCandy: ImageName.asianCandy.rawValue,
                               imageDish: ImageName.asian3.rawValue,
                               nameOfDish: "Phoenix Blossom Almond Cake",
                               historyOfDish: "The Phoenix Blossom Almond Cake was created by a creative baker named Lin Mei, who grew up in the picturesque city of Suzhou, known for its beautiful gardens and canals. Inspired by the elegance and beauty of the phoenix, a symbol of grace and rebirth in Chinese culture, Lin Mei wanted to create a dessert that embodied these qualities. She combined the nutty flavor of almonds with the delicate sweetness of honey and the lightness of sponge cake to create a delightful and visually stunning cake. The Phoenix Blossom Almond Cake quickly became a favorite at weddings and special occasions and is now a beloved dessert across China.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.\n\u{2022} In a large bowl, combine the flour, sugar, almond flour, baking powder, baking soda, and salt.\n\u{2022} In another bowl, mix the eggs, vegetable oil, milk, vanilla extract, and almond extract.\n\u{2022} Combine the wet and dry ingredients and mix until smooth.\n\u{2022} Pour the batter into the prepared pans and bake for 25-30 minutes, or until a toothpick inserted into the center comes out clean.\n\u{2022} Allow the cakes to cool completely.",
                               ingredients: "\u{2022} 1 1/2 cups all-purpose flour\n\u{2022} 1 cup granulated sugar\n\u{2022} 1 cup almond flour\n\u{2022} 1 teaspoon baking powder\n\u{2022} 1/2 teaspoon baking soda\n\u{2022} 1/2 teaspoon salt\n\u{2022} 4 large eggs\n\u{2022} 1/2 cup vegetable oil\n\u{2022} 1/2 cup milk",
                                      height: 0.27,
                               quizz: Quizzes(questions: ["Who created the Phoenix Blossom Almond Cake?",
                                                          "What inspired the creation of the Phoenix Blossom Almond Cake?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A creative baker named Lin Mei",
                                                         "C. A renowned pastry chef from Beijing",
                                                         "D. A Chinese celebrity"],
                                                        
                                                        ["A. The elegance and beauty of the phoenix",
                                                         "B. The bustling markets of Shanghai",
                                                         "C. The cool climate of the mountains",
                                                         "D. The significance of the dragon in Chinese culture"]],
                                              rightAnswers: ["B. A creative baker named Lin Mei",
                                                             "A. The elegance and beauty of the phoenix"]))
    
    var america1 = DishAndQiuzz(imageNameContry: ImageName.americaLabel.rawValue,
                                imageForFav: ImageName.american1.rawValue,
                               imageCandy: ImageName.candyAmerica.rawValue,
                               imageDish: ImageName.america1.rawValue,
                               nameOfDish: "Stars and Stripes Cupcakes",
                               historyOfDish: "The Stars and Stripes Cupcakes were created by a talented baker named Emily, who grew up in a small town in Iowa. Inspired by the patriotic spirit of her community and the vibrant colors of the American flag, Emily wanted to create a dessert that celebrated the pride and unity of her country. She combined a classic vanilla cupcake with a creamy buttercream frosting, decorated with red, white, and blue sprinkles to represent the stars and stripes of the flag. These cupcakes quickly became a hit at local Fourth of July celebrations and are now a beloved treat across the United States.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Line a muffin tin with cupcake liners.\n\u{2022} In a large bowl, combine the flour, sugar, baking powder, and salt.\n\u{2022} In another bowl, cream the butter until light and fluffy.\n\u{2022} Add the eggs, one at a time, mixing well after each addition.\n\u{2022} Stir in the vanilla extract.\n\u{2022} Gradually add the dry ingredients to the wet ingredients, alternating with the milk, beginning and ending with the dry ingredients.",
                               ingredients: "\u{2022} 1 1/2 cups all-purpose flour\n\u{2022} 1 cup granulated sugar\n\u{2022} 1 1/2 teaspoons baking powder\n\u{2022} 1/2 teaspoon salt\n\u{2022} 1/2 cup unsalted butter, softened\n\u{2022} 2 large eggs\n\u{2022} 2 teaspoons vanilla extract\n\u{2022} 1/2 cup milk",
                                      height: 0.36,
                               quizz: Quizzes(questions: ["Who created the Stars and Stripes Cupcakes?",
                                                          "What inspired the creation of the Stars and Stripes Cupcakes?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A talented baker named Emily",
                                                         "C. A renowned pastry chef from New York",
                                                         "D. An American celebrity"],
                                                        
                                                        ["A. The patriotic spirit of the community",
                                                         "B. The bustling markets of Chicago",
                                                         "C. The cool climate of the mountains",
                                                         "D. The significance of the eagle in American culture"]],
                                              rightAnswers: ["B. A talented baker named Emily",
                                                             "A. The patriotic spirit of the community"]))
    
    var america2 = DishAndQiuzz(imageNameContry: ImageName.americaLabel.rawValue,
                                imageForFav: ImageName.american2.rawValue,
                                imageCandy: ImageName.candyAmerica.rawValue,
                               imageDish: ImageName.america2.rawValue,
                               nameOfDish: "Red Velvet Patriot Cupcakes",
                               historyOfDish: "TThe Stars and Stripes Cupcakes were created by a talented baker named Emily, who grew up in a small town in Iowa. Inspired by the patriotic spirit of her community and the vibrant colors of the American flag, Emily wanted to create a dessert that celebrated the pride and unity of her country. She combined a classic vanilla cupcake with a creamy buttercream frosting, decorated with red, white, and blue sprinkles to represent the stars and stripes of the flag. These cupcakes quickly became a hit at local Fourth of July celebrations and are now a beloved treat across the United States.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Line a muffin tin with cupcake liners.\n\u{2022} In a large bowl, combine the flour, sugar, baking powder, and salt.\n\u{2022} In another bowl, cream the butter until light and fluffy.\n\u{2022} Add the eggs, one at a time, mixing well after each addition.\n\u{2022} Stir in the vanilla extract.\n\u{2022} Gradually add the dry ingredients to the wet ingredients, alternating with the milk, beginning and ending with the dry ingredients.",
                               ingredients: "\u{2022} 1 1/2 cups all-purpose flour\n\u{2022} 1 cup granulated sugar\n\u{2022} 1 1/2 teaspoons baking powder\n\u{2022} 1/2 teaspoon salt\n\u{2022} 1/2 cup unsalted butter, softened\n\u{2022} 2 large eggs\n\u{2022} 2 teaspoons vanilla extract\n\u{2022} 1/2 cup milk",
                                      height: 0.36,
                               quizz: Quizzes(questions: ["Who created the Stars and Stripes Cupcakes?",
                                                          "What inspired the creation of the Stars and Stripes Cupcakes?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A talented baker named Emily",
                                                         "C. A renowned pastry chef from New York",
                                                         "D. An American celebrity"],
                                                        
                                                        ["A. The patriotic spirit of the community",
                                                         "B. The bustling markets of Chicago",
                                                         "C. The cool climate of the mountains",
                                                         "D. The significance of the eagle in American culture"]],
                                              rightAnswers: ["B. A talented baker named Emily",
                                                             "A. The patriotic spirit of the community"]))
    
    var america3 = DishAndQiuzz(imageNameContry: ImageName.americaLabel.rawValue,
                                imageForFav: ImageName.american3.rawValue,
                               imageCandy: ImageName.candyAmerica.rawValue,
                               imageDish: ImageName.america3.rawValue,
                               nameOfDish: "Chocolate Freedom Cupcakes",
                               historyOfDish: "The Chocolate Freedom Cupcakes were created by a creative baker named Michael, who grew up in the historic city of Philadelphia. Inspired by the spirit of freedom and independence that defines the United States, Michael wanted to create a dessert that embodied these values. He combined the rich flavors of chocolate with a creamy chocolate buttercream frosting and decorated the cupcakes with red, white, and blue accents to symbolize the colors of liberty. These cupcakes quickly became a favorite at patriotic celebrations and are now enjoyed across the country.",
                               receptOfDish: "\u{2022} Preheat the oven to 350°F (175°C). Line a muffin tin with cupcake liners.\n\u{2022} In a large bowl, combine the flour, sugar, cocoa powder, baking soda, and salt.\n\u{2022} Make three wells in the dry ingredients and pour the vegetable oil into one, the vanilla extract into another, and the vinegar into the last one.\n\u{2022} Pour the water over everything and mix until smooth.\n\u{2022} Fill the cupcake liners 2/3 full with batter and bake for 18-20 minutes, or until a toothpick inserted into the center comes out clean.",
                               ingredients: "\u{2022} 1 1/2 cups all-purpose flour\n\u{2022} 1/4 cup unsweetened cocoa powder\n\u{2022} 1 teaspoon baking soda\n\u{2022} 1/2 teaspoon salt\n\u{2022} 1/3 cup vegetable oil\n\u{2022} 1 teaspoon vanilla extract\n\u{2022} 1 tablespoon white vinegar\n\u{2022} 1 cup water",
                                      height: 0.36,
                               quizz: Quizzes(questions: ["Who created the Chocolate Freedom Cupcakes?",
                                                          "What inspired the creation of the Chocolate Freedom Cupcakes?"],
                                              answers: [["A. A famous TV chef",
                                                         "B. A talented baker named Emily",
                                                         "C. A renowned pastry chef from Chicago",
                                                         "D. An American celebrity"],
                                                        
                                                        ["A. The patriotic spirit of the community",
                                                         "B. The bustling markets of Chicago",
                                                         "C. The cool climate of the mountains",
                                                         "D. The significance of the eagle in American culture"]],
                                              rightAnswers: ["B. A talented baker named Emily",
                                                             "A. The patriotic spirit of the community"]))
}


